name: Draft Shuai Clock Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  create-release:
    name: Create draft release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Create draft release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Shuai Clock ${{ github.ref }}
        draft: true
        prerelease: false
  build:
    name: Build application
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target: [macos, windows, linux, apk]
        include:
        - os: macos-latest
          target: macos
          path: build/macos/Build/Products/Release
        - os: windows-2019
          target: windows
          path: build\windows\runner\Release
        - os: ubuntu-latest
          target: linux
          path: build/linux/release/bundle
        - os: ubuntu-latest
          target: apk
          path: build/app/outputs/apk/release/
        - os: ubuntu-latest
          target: appbundle
          path: build/app/outputs/apk/release/
      # Disable fail-fast as we want results from all even if one fails.
      fail-fast: false
    needs: create-release
    steps:
    # Set up Flutter and add it to the path.
    - name: Clone Flutter repository with master channel
      uses: actions/checkout@v2
      with:
        repository: 'flutter/flutter'
        ref: 'dev'
        path: 'flutter'
        fetch-depth: 0
    - name: Add Flutter to the PATH for Linux and macOS
      if: startsWith(matrix.os, 'macOS') || startsWith(matrix.os, 'ubuntu')
      run: echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
    - name: Add Flutter to the PATH for Windows
      if: startsWith(matrix.os, 'windows')
      run: echo "${env:GITHUB_WORKSPACE}\flutter\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Install Linux dependencies
      if: startsWith(matrix.target, 'linux')
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev
    - name: Install Android dependencies
      if: startsWith(matrix.target, 'apk')
      uses: actions/setup-java@v1
      with:
        java-version: '11.x'
    - name: Enable desktop support
      run: |
        flutter config --enable-linux-desktop
        flutter config --enable-macos-desktop
        flutter config --enable-windows-desktop
    - name: Run Flutter doctor
      run: flutter doctor -v

    # Clone the ShuaiClock repository under `code`, to avoid conflicts with `flutter`.
    - name: Clone the ShuaiClock repository
      uses: actions/checkout@v2
      with:
        path: 'code'
    - name: Get packages for the Flutter project
      run: flutter pub get
      working-directory: code
    - name: Env Init
      run: |
        echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > android/app/${{secrets.KEY_PATH}}
      working-directory: code
    # Build the application for desktop.
    - name: Build project Windows Linux and macOS
      if: startsWith(matrix.os, 'macOS') || startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'windows')
      run: |
        flutter create .
        flutter build -v ${{ matrix.target }} --release
      working-directory: code
    - name: Build project apk
      if: startsWith(matrix.target, 'apk')
      run: |
        flutter build -v ${{ matrix.target }} --obfuscate --split-per-abi --split-debug-info=./info --release
      env:
        KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PATH: ${{ secrets.KEY_PATH }}
      working-directory: code
    - name: Build project appbundle
      if: startsWith(matrix.target, 'appbundle')
      run: |
        flutter build -v ${{ matrix.target }} --obfuscate --split-debug-info=./info --release
      env:
        KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PATH: ${{ secrets.KEY_PATH }}
      working-directory: code
    - name: Copy VC redistributables to release directory
      if: startsWith(matrix.target, 'windows')
      run: |
        Copy-Item (vswhere -find 'VC\Redist\MSVC\14.27.29016\x64\Microsoft.VC142.CRT\msvcp140.dll') .
        Copy-Item (vswhere -find 'VC\Redist\MSVC\14.27.29016\x64\Microsoft.VC142.CRT\vcruntime140.dll') .
        Copy-Item (vswhere -find 'VC\Redist\MSVC\14.27.29016\x64\Microsoft.VC142.CRT\vcruntime140_1.dll') .
      working-directory: code\${{ matrix.path }}
    - name: Compress build for Linux and macOS
      if: startsWith(matrix.os, 'macOS') || startsWith(matrix.os, 'ubuntu')
      run: zip -r $GITHUB_WORKSPACE/shuaiclock_${{ matrix.target }} .
      working-directory: code/${{ matrix.path }}
    - name: Compress build for Windows
      if: startsWith(matrix.os, 'windows')
      run: compress-archive -Path * -DestinationPath ${env:GITHUB_WORKSPACE}\shuaiclock_${{ matrix.target }}.zip
      working-directory: code\${{ matrix.path }}
    - name: Upload release asset
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ./shuaiclock_${{ matrix.target }}.zip
        asset_name: shuaiclock_${{ matrix.target }}.zip
        asset_content_type: application/zip