name: Flutter-PackageCI

on:
  release:
    branches: [ master ]
    
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - uses: subosito/flutter-action@v1.3.2
      with:
        flutter-version: '1.18.0-11.1.pre'
        channel: 'beta'
    - run: flutter pub get
    - run: flutter doctor -v
    - run: flutter build apk
    - name: Setup Go environment
      uses: actions/setup-go@v2.0.3
      with:
        go-version: 1.14.1
        stable: true 
    - run: go version
        
